modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
issueTrackerURL = "https://github.com/Volcano-Bay-Studios/superposition/issues"
license = "${mod_license}"

[[mods]]
modId = "superposition"
version = "${version}"
displayName = "${mod_name}"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://github.com/Volcano-Bay-Studios/superposition"
logoFile = "superposition.png"
#credits="Thanks for this example mod goes to Java"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.superposition]]
modId = "forge"
mandatory = true
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.superposition]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.superposition]]
modId = "veil"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"